cmd_/builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/objtool/weak.o := gcc -Wp,-MD,/builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/objtool/.weak.o.d -Wp,-MT,/builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/objtool/weak.o -Werror -Wbad-function-cast -Wdeclaration-after-statement -Wformat-security -Wformat-y2k -Winit-self -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-system-headers -Wold-style-definition -Wpacked -Wredundant-decls -Wstrict-prototypes -Wswitch-default -Wswitch-enum -Wundef -Wwrite-strings -Wformat -Wstrict-aliasing=3 -Wshadow -Wno-switch-default -Wno-switch-enum -Wno-packed -Wno-nested-externs -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -fomit-frame-pointer -std=gnu89 -O2 -I/builder/shared-workdir/build/staging_dir/host/include -Wall -Wmissing-prototypes -Wstrict-prototypes -g -I/builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/include -I/builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/arch/x86/include/uapi -I/builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/arch/x86/include -I/builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/objtool/arch/x86/include -I/builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/lib -D"BUILD_STR(s)=$(pound)s" -c -o /builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/objtool/weak.o weak.c

source_/builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/objtool/weak.o := weak.c

deps_/builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/objtool/weak.o := \
  /usr/include/stdc-predef.h \
  /usr/lib/gcc/x86_64-linux-gnu/8/include/stdbool.h \
  /usr/include/errno.h \
  /usr/include/features.h \
  /usr/include/x86_64-linux-gnu/sys/cdefs.h \
  /usr/include/x86_64-linux-gnu/bits/wordsize.h \
  /usr/include/x86_64-linux-gnu/bits/long-double.h \
  /usr/include/x86_64-linux-gnu/gnu/stubs.h \
  /usr/include/x86_64-linux-gnu/gnu/stubs-64.h \
  /usr/include/x86_64-linux-gnu/bits/errno.h \
  /usr/include/linux/errno.h \
  /builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/arch/x86/include/uapi/asm/errno.h \
  /usr/include/asm-generic/errno.h \
  /usr/include/asm-generic/errno-base.h \
  objtool.h \
  /builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/include/linux/list.h \
  /builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/include/linux/types.h \
  /usr/lib/gcc/x86_64-linux-gnu/8/include/stddef.h \
  /usr/lib/gcc/x86_64-linux-gnu/8/include/stdint.h \
  /usr/include/stdint.h \
  /usr/include/x86_64-linux-gnu/bits/libc-header-start.h \
  /usr/include/x86_64-linux-gnu/bits/types.h \
  /usr/include/x86_64-linux-gnu/bits/typesizes.h \
  /usr/include/x86_64-linux-gnu/bits/wchar.h \
  /usr/include/x86_64-linux-gnu/bits/stdint-intn.h \
  /usr/include/x86_64-linux-gnu/bits/stdint-uintn.h \
  /usr/include/x86_64-linux-gnu/asm/types.h \
  /usr/include/asm-generic/types.h \
  /usr/include/asm-generic/int-ll64.h \
  /builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/arch/x86/include/uapi/asm/bitsperlong.h \
  /builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/include/asm-generic/bitsperlong.h \
  /builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/include/uapi/asm-generic/bitsperlong.h \
  /usr/include/x86_64-linux-gnu/asm/posix_types.h \
  /usr/include/x86_64-linux-gnu/asm/posix_types_64.h \
  /usr/include/asm-generic/posix_types.h \
  /builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/include/linux/poison.h \
  /builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/include/linux/kernel.h \
  /usr/lib/gcc/x86_64-linux-gnu/8/include/stdarg.h \
  /usr/include/assert.h \
  /builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/include/linux/build_bug.h \
  /builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/include/linux/compiler.h \
  /builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/include/linux/compiler-gcc.h \
  /builder/shared-workdir/build/staging_dir/host/include/endian.h \
  /builder/shared-workdir/build/staging_dir/host/include/byteswap.h \
  /usr/include/byteswap.h \
  /usr/include/x86_64-linux-gnu/bits/byteswap.h \
  /usr/include/endian.h \
  /usr/include/x86_64-linux-gnu/bits/endian.h \
  /usr/include/x86_64-linux-gnu/bits/uintn-identity.h \
  /builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/include/linux/hashtable.h \
  /builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/include/linux/bitops.h \
  /usr/lib/gcc/x86_64-linux-gnu/8/include-fixed/limits.h \
  /usr/lib/gcc/x86_64-linux-gnu/8/include-fixed/syslimits.h \
  /usr/include/limits.h \
  /usr/include/x86_64-linux-gnu/bits/posix1_lim.h \
  /usr/include/x86_64-linux-gnu/bits/local_lim.h \
  /usr/include/linux/limits.h \
  /usr/include/x86_64-linux-gnu/bits/posix2_lim.h \
  /builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/include/linux/bits.h \
  /builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/include/linux/const.h \
  /builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/include/vdso/const.h \
  /builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/include/uapi/linux/const.h \
  /builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/include/vdso/bits.h \
  /builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/include/asm-generic/bitops.h \
  /builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/include/asm-generic/bitops/__ffs.h \
  /builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/include/asm-generic/bitops/__ffz.h \
  /builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/include/asm-generic/bitops/fls.h \
  /builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/include/asm-generic/bitops/__fls.h \
  /builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/include/asm-generic/bitops/fls64.h \
  /builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/include/asm-generic/bitops/find.h \
  /builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/include/asm-generic/bitops/hweight.h \
  /builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/include/asm-generic/bitops/arch_hweight.h \
  /builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/include/asm-generic/bitops/const_hweight.h \
  /builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/include/asm-generic/bitops/atomic.h \
  /builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/include/asm-generic/bitops/non-atomic.h \
  /builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/include/linux/hash.h \
  /builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/include/linux/log2.h \
  elf.h \
  /usr/include/stdio.h \
  /usr/include/x86_64-linux-gnu/bits/types/__fpos_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/__fpos64_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/__FILE.h \
  /usr/include/x86_64-linux-gnu/bits/types/FILE.h \
  /usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h \
  /usr/include/x86_64-linux-gnu/bits/stdio_lim.h \
  /usr/include/x86_64-linux-gnu/bits/sys_errlist.h \
  /usr/include/x86_64-linux-gnu/bits/stdio.h \
  /usr/include/gelf.h \
  /usr/include/libelf.h \
  /usr/include/x86_64-linux-gnu/sys/types.h \
  /usr/include/x86_64-linux-gnu/bits/types/clock_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/clockid_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/time_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/timer_t.h \
  /usr/include/x86_64-linux-gnu/sys/select.h \
  /usr/include/x86_64-linux-gnu/bits/select.h \
  /usr/include/x86_64-linux-gnu/bits/types/sigset_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/__sigset_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/struct_timeval.h \
  /usr/include/x86_64-linux-gnu/bits/types/struct_timespec.h \
  /usr/include/x86_64-linux-gnu/bits/pthreadtypes.h \
  /usr/include/x86_64-linux-gnu/bits/thread-shared-types.h \
  /usr/include/x86_64-linux-gnu/bits/pthreadtypes-arch.h \
  /builder/shared-workdir/build/staging_dir/host/include/elf.h \
  /builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/include/linux/rbtree.h \
  /usr/include/linux/stddef.h \
  /builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/include/linux/jhash.h \
  /builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/include/linux/unaligned/packed_struct.h \

/builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/objtool/weak.o: $(deps_/builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/objtool/weak.o)

$(deps_/builder/shared-workdir/build/build_dir/target-x86_64_musl/linux-x86_64/linux-5.10.161/tools/objtool/weak.o):
