name: ipk-build-bot
on:
  schedule:
    - cron: '0 9 * * *'


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: build-ipks
      run: |
        pushd openwrt-sdk-22.03.3-x86-64_gcc-11.2.0_musl.Linux-x86_64
        # make package/shadowsocks-libev/{clean,compile} V=99 -j64
        make package/chinadns-ng/compile V=99 -j64
        make package/v2ray-plugin/compile V=99 -j64
        popd
    - name: Check changes
      id: check_changes
      run: |
        if [[ -z $(git status -s) ]]; then
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi
    - name: Commit files
      env:
          GITHUB_TOKEN: ${{ secrets.action_bot }}
      if: steps.check_changes.outputs.changed == 'true'
      run: |
        git config --global user.name 'action-bot'
        git config --global user.email 'action-bot@nowhere.com'
        git add .
        git commit -m 'update by bot'
        git push
    - name: Send email
      if: steps.check_changes.outputs.changed == 'true'
      run: |
        python3 send_email.py ${{ secrets.msg_secret }} "ipk have updates" "ipk(s) have updates, please check!"
